name = "lapce-python"
version = "0.3.4"
author = "various"
display-name = "Python (python-lsp-server)"
description = "Python for Lapce using python-lsp-server"
wasm = "lapce-python.wasm"
icon = "python-logo-only.png"

[activation]
language = ["python"]

[config."serverPath"]
default = ""
description = "Path to python-language-server. When empty, will attempt to automatically locate binary"
